### ISSUE TITLE
Example not working after `pip install` with requirements

### ISSUE THREAD

**Issue by bhoov** [YingfanWang/PaCMAP#1]
Really cool work! I look forward to exploring more.

It looks like the example on the README does not work with the `pacmap` installed from pip. I get the following error:

```
    361         self.n_dims = n_dims
    362         self.n_neighbors = n_neighbors
--> 363         self.n_MN = int((n_neighbors * MN_ratio) // 1)
    364         self.n_FP = int((n_neighbors * FP_ratio) // 1)
    365         self.pair_neighbors = pair_neighbors

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

After fixing this by putting in setting `n_neighbors=10`, I find the following error dealing with dimensions of the data:

```
    257 ):
    258     start_time = time.time()
--> 259     n, high_dim = X.shape
    260 
    261     if intermediate:

ValueError: too many values to unpack (expected 2)
```

The shape of the `data/coil_20.npy` file stored in github (`(1440, 128, 128)`) is inconsistent with that expected by the example code.

Thanks!

**Comment by hyhuang00** [comment]
Thank you for bringing this up! There is an inconsistency in the api between the pip version and the version that is currently on GitHub, which leads to the TypeError you got. We will update the pip version (and also the example code) ASAP to reflect these changes.

**Comment by hyhuang00** [comment]
The sample code has been temporarily modified to be consistent with the pip version.

**Comment by bhoov** [comment]
Thank you, the new example code works with my env now :)
