### ISSUE TITLE
AttributeError: module 'pacmap' has no attribute 'PaCMAP'

### ISSUE THREAD

**Issue by kengcher** [YingfanWang/PaCMAP#11]
Hi 

I was trying to run pacmap but i ran into the following error:

Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pacmap
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> 
>>> # loading preprocessed coil_20 dataset
... # you can change it with any dataset that is in the ndarray format, with the shape (N, D)
... # where N is the number of samples and D is the dimension of each sample
... X = np.load("./data/coil_20.npy", allow_pickle=True)
>>> X = X.reshape(X.shape[0], -1)
>>> y = np.load("./data/coil_20_labels.npy", allow_pickle=True)
>>> embedding = pacmap.PaCMAP(n_dims=2, n_neighbors=None, MN_ratio=0.5, FP_ratio=2.0) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pacmap' has no attribute 'PaCMAP'

Please advise.

Thank you.

**Comment by hyhuang00** [comment]
We haven't encountered such error before. Could you provide the following information:

- How did you install pacmap? Though the version on PyPI should be consistent with this repo, installing from this repo hasn't be tested yet.
- What is the version of pacmap you are using? You can check it by opening the IPython interface, import pacmap, and then enter `pacmap.__version__`

**Comment by kengcher** [comment]
Hi Haiyang 

i installed it using pip in my conda env and >>> pacmap.__version__
'0.4'

**Comment by hyhuang00** [comment]
> Hi Haiyang
> 
> i installed it using pip in my conda env and >>> pacmap.**version**
> '0.4'

That's weird. Could you also try to do the following thing in your Python script:
- `import pacmap`
- Use 'pacmap.pacmap.PaCMAP' instead of `pacmap.PaCMAP`
and see how it works?

**Comment by kengcher** [comment]
very weird indeed. pacmap.pacmap.PaCMAP does not work either

>>> embedding = pacmap.pacmap.PaCMAP(n_dims=2, n_neighbors=None, MN_ratio=0.5, FP_ratio=2.0) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pacmap' has no attribute 'pacmap'
>>> embedding = pacmap.__
pacmap.__cached__          pacmap.__doc__             pacmap.__getattribute__(   pacmap.__le__(             pacmap.__new__(            pacmap.__repr__(           pacmap.__subclasshook__(
pacmap.__class__(          pacmap.__eq__(             pacmap.__gt__(             pacmap.__loader__          pacmap.__package__         pacmap.__setattr__(        
pacmap.__delattr__(        pacmap.__file__            pacmap.__hash__(           pacmap.__lt__(             pacmap.__path__            pacmap.__sizeof__(         
pacmap.__dict__            pacmap.__format__(         pacmap.__init__(           pacmap.__name__            pacmap.__reduce__(         pacmap.__spec__            
pacmap.__dir__(            pacmap.__ge__(             pacmap.__init_subclass__(  pacmap.__ne__(             pacmap.__reduce_ex__(      pacmap.__str__(

**Comment by kengcher** [comment]
i think it is a silly issue caused by where i run the command! if i am in the root PaCMAP dir i would need to import pacmap.pacmap

Thank you.

**Comment by catubc** [comment]
For others who are stuck on running the sample code.

You need to import submodule. So instead of

import pacmap

Do:

from pacmap import pacmap

And the the rest of the sample code should work.

**Comment by hyhuang00** [comment]
> For others who are stuck on running the sample code.
> 
> You need to import submodule. So instead of
> 
> import pacmap
> 
> Do:
> 
> from pacmap import pacmap
> 
> And the the rest of the sample code should work.

Thanks for reporting the problem! It seems like this problem is due to a bug in version 0.4.1. We will try to fix this as soon as possible!

**Comment by hyhuang00** [comment]
The problem has been resolved now. Due to an incompatibility issue between numba and NumPy, the package now requires Numpy >= 1.20 and numba >= 0.50. For users that have earlier versions, we suggest you to use pacmap v0.4.

**Comment by PieterMey** [comment]
I am having similar issues with pacmap 0.5.2.1. I have installed all modules via pip. Currently:
numpy - 1.20.3
numba - 0.54.0
pacmap - 0.5.2.1
python - 3.8.3

I have tried using import pacmap as well as from pacmap import pacmap. The same error occurs of: 

AttributeError: module 'pacmap' has no attribute 'PaCMAP'

**Comment by hyhuang00** [comment]
Did you manage to resolve this issue? I cannot see your comment on GitHub.
