### ISSUE TITLE
Paper already peer reviewed and published?

### ISSUE THREAD

**Issue by robvanvolt** [YingfanWang/PaCMAP#13]
As for citing your brilliant work, it would really help if the paper was already published (not only as a preprint) - how far is the progress on that matter?:)

**Comment by hyhuang00** [comment]
Thank you for your interest! Our work has been peer reviewed and accepted by the Journal of Machine Learning Research, and we are currently in the process of preparing the camera-ready version. We will update both the citation link and description once the final version is ready!
