### ISSUE TITLE
Doesn't work in sklearn's Pipeline

### ISSUE THREAD

**Issue by jochenater** [YingfanWang/PaCMAP#15]
`pipe = Pipeline([('reduce_dim', pacman()),
                 ('kmeans, KMeans())])`

AttributeError: 'PaCMAP' object has no attribute 'random_state'

Would be great if it did

**Comment by hyhuang00** [comment]
Could you report the version of your PaCMAP? In some cases, update to the newest version via `pip install --upgrade pacmap` could solve the problem.

**Comment by jochenater** [comment]
I just installed it today so should be the newest version:
0.5.2

**Comment by hyhuang00** [comment]
I see. I have reproduced your error locally. Let me try to fix this.

**Comment by hyhuang00** [comment]
The problem with the current version of PaCMAP is that the `random_state` parameter got renamed into `seed` into the PaCMAP instance. When you try to print the PaCMAP instances, however, the sklearn convention will ask the instance to print all its parameter as is. I will try to bring up a hotfix later today. To use the PaCMAP before the hotfix released, please try to avoid printing it out (e.g. `pacman = pacmap.PaCMAP()`)

**Comment by hyhuang00** [comment]
A hotfix have been pushed to the PyPI. However, given that current PaCMAP algorithm is transductive instead of inductive, it does not implement `transform()` method (just as the sklearn TSNE implementation), which means you will still be unable to use it in Pipeline. Please try to use the workaround provide in my last comment.

**Comment by jochenater** [comment]
Thanks for the quick fix!
I've just seen the other issue about the lack of transform method. I think it would greatly improve the usability if it had one ;)

**Comment by jochenater** [comment]
For people that just need to use it in their pipeline, here is some ugly hack:

`pacman = PaCMAP()
def transform(self, *args, **kwargs):
    return self.fit_transform(*args, **kwargs)
pacman.transform = transform.__get__(pacman)`

**Comment by hyhuang00** [comment]
The `transform` method has been added in the latest release.
