### ISSUE TITLE
Sample code does not work

### ISSUE THREAD

**Issue by CoteDave** [YingfanWang/PaCMAP#30]
![image](https://user-images.githubusercontent.com/49559881/163173780-2ed704e2-3ca0-49e4-bd20-87a2194ae4a9.png)

results:

![image](https://user-images.githubusercontent.com/49559881/163173850-82fb0a62-1b40-4fb4-afd2-c52f605a3e8b.png)

if I change n_dims for n_components it works, but when I fit:
![image](https://user-images.githubusercontent.com/49559881/163174091-af2a1d53-fa29-4566-b4df-bcbe33cbc0ac.png)

![image](https://user-images.githubusercontent.com/49559881/163174122-3bf3a231-d667-4912-898e-223d9fc98620.png)

Thanks!

**Comment by hyhuang00** [comment]
Thank you for bringing this up! v0.6.1 includes a bug that have been fixed by #29. It has been fixed in v0.6.2. The demo file is currently deprecated as I renamed some of the variables in the latest release, and I will update the demo files asap.

**Comment by hyhuang00** [comment]
The demo file has been updated.
