### ISSUE TITLE
transform() only produces constant when save_tree = True

### ISSUE THREAD

**Issue by nfultz** [YingfanWang/PaCMAP#31]
I have an example of using the new transform() feature on iris at :

https://colab.research.google.com/drive/1T3ALLtbx8kw9NAoZzvJQSFgiWvHOvIvM?usp=sharing

It appears to only generate a constant when save_tree is set.

I had expected calling transform() on the iris data to be equivalent to the result of fit_transform()

Or perhaps I read the docstring wrong and there is a different calling convention?

**Comment by hyhuang00** [comment]
For an already fitted dataset, the results can be retrieved by calling `embedding = pacmap.embedding_`. The `transform()` method are usually used for dataset that have not been fitted at all. That being said, generating constant is unexpected -- theoretically, the way you conduct experiment should return something very similar, but not exactly the same as the `fit_transform()` output. Let me take a look and see why this happens.

**Comment by hyhuang00** [comment]
Should have been fixed now.

**Comment by nfultz** [comment]
I can see this fixed when I reran the example notebook, thanks much!
