### ISSUE TITLE
Readme n_dims vs. n_components 

### ISSUE THREAD

**Issue by AndreasGerken** [YingfanWang/PaCMAP#39]
In the example in REAMDE.md, the PaCMAP object is initialized with

```
embedding = pacmap.PaCMAP(n_dims=2, n_neighbors=None, MN_ratio=0.5, FP_ratio=2.0) 
````

This produces an error `TypeError: __init__() got an unexpected keyword argument 'n_dims'`.
Probably it should be `n_comonents` instead of `n_dims`.

**Comment by hyhuang00** [comment]
Thank you! This problem has been resolved.
