### ISSUE TITLE
Clarify options for init argument

### ISSUE THREAD

**Issue by cciccole** [YingfanWang/PaCMAP#5]
In the readme it says `init: the initialization of the lower dimensional embedding. One of "pca" or "random". Default to "pca".`

Looking through the code it seems like init can also be a user-supplied matrix. If that's true, the readme should be corrected and the code should be updated to check that the number of columns and rows in the user-supplied matrix is acceptable, and if not, a specific error should be thrown.

**Comment by cciccole** [comment]
@hyhuang00 bump.

I'll add that I'm a bit surprised about this given how thorough the paper is on the topic of initialization. Let me know if I'm missing something.

**Comment by hyhuang00** [comment]
The readme has been updated and we are now supporting using user-supplied matrix for initialization. A scaling will be performed to the user-supplied initialization to ensure the scale matches with the force of PaCMAP.
