### ISSUE TITLE
Is `inverse_transform` possible with PaCMAP?

### ISSUE THREAD

**Issue by MattWenham** [YingfanWang/PaCMAP#50]
Is `inverse_transform` possible with PaCMAP?

I appreciate that it hasn't been implemented as yet, but it can be very useful when assessing how well the model is capturing the subtleties of the input data. However, for certain techniques, it's simply not possible.

If it's possible, I will open an enhancement request 😊

**Comment by hyhuang00** [comment]
The PaCMAP itself is a non-parametric DR method, so I think it is impossible to directly perform the `inverse_transform` in a way that ensures the resulting point will get mapped into the input in the low-dimensional space. What is possible instead is that we could create a surrogate method to perform the `inverse_transform`, though, by creating pairs in the low-dim space and try to render the relationships in the high-dim space. Would you be able to specify how you would like to assess the capturing of subtleties in the input data? We could also try to design some other features that renders information for this purpose as well.
