### ISSUE TITLE
Add PaCMAP to Conda-forge please

### ISSUE THREAD

**Issue by helios1014** [YingfanWang/PaCMAP#51]
Hello, can you add this package to conda-forge or are there issues that are still being worked out?

If you nee directions, you can look here: https://github.com/conda-forge/staged-recipes

**Comment by hyhuang00** [comment]
Thank you for the pointers. We are trying to add this package to conda-forge, and we will update this issue once the pull request has been approved.

**Comment by hyhuang00** [comment]
PaCMAP is now available on conda. Closing this issue.
