### ISSUE TITLE
Failed to install PaCMAP with pip

### ISSUE THREAD

**Issue by Thiziri-Hafir** [YingfanWang/PaCMAP#54]
hello, we're two users trying to install the library for the first time but without succes. Does anyone know how to solve the problem.

**Comment by nirbhayjm** [comment]
I have also experienced this error -- `pip install pacmap` doesn't work due to a `Failed to build annoy` error, likely due to mismatch of c++ libraries. I was able to fix this by first installing annoy through conda.

```
conda install -c conda-forge python-annoy
pip install pacmap
```

**Comment by hyhuang00** [comment]
Thank you for sharing your experience and solution! I agree there might be some problems with the C++ dependencies. Will try to replicate the issue on a local environment.

**Comment by hyhuang00** [comment]
I am unable to replicate this issue locally, so I guess the problem depends on the user's local environment. We have updated the README accordingly, and thank you for your help!
