### ISSUE TITLE
Cosine distance has a call to sqrt

### ISSUE THREAD

**Issue by danr** [YingfanWang/PaCMAP#60]
https://github.com/YingfanWang/PaCMAP/blob/8e22b7cb48ccbbbcb3feae90db79a2eaac19cf14/source/pacmap/pacmap.py#L53-L63

Cosine distance as defined does not have a square root call. I think the `np.sqrt` should be removed here.

**Comment by hyhuang00** [comment]
Hi Dan! Thank you for your interest in PaCMAP!

Here, we chose to follow the definition of angular distance provided in [`annoy`](https://github.com/spotify/annoy) for consistency. The angular distance is defined as the Euclidean distance of the two normalized vector `u, v`.

`euclidean(u, v) = sqrt(u^2 + v^2 - 2uv) = sqrt(2-2uv) = sqrt(2-2 cos theta)`

Let me know if you have further questions!

**Comment by danr** [comment]
Thanks, then it makes sense!
