### ISSUE TITLE
Inconsistent gradient calculations

### ISSUE THREAD

**Issue by michael-long88** [YingfanWang/PaCMAP#69]
When looking through the source code, I noticed that in [pacmap_grad](https://github.com/YingfanWang/PaCMAP/blob/fa05b265371c356611cd2a7a729fadedc2c5a534/source/pacmap/pacmap.py#L234), there seems to be an inconsistency when calculating the gradients for the different pairs. 

For nearest neighbor and mid-near pairs, the gradient calculation looks like
```Python
grad[i, d] += w1 * y_ij[d]
grad[j, d] -= w1 * y_ij[d]
```
but for further pairs, it's
```Python
grad[i, d] -= w1 * y_ij[d]
grad[j, d] += w1 * y_ij[d]
```
where you're subtracting for `i` and adding for `j` instead of the other way around. Is this a typo, or a legitimate change in the calculation?

**Comment by hyhuang00** [comment]
It's a legitimate change. Further pairs are supposed to push points apart.
