### ISSUE TITLE
Can't find mammoth_data.csv

### ISSUE THREAD

**Issue by wichaidi** [YingfanWang/PaCMAP#73]
Hi -

I am trying to follow an example from Rnotebook_example (https://github.com/YingfanWang/PaCMAP/blob/master/demo/pacmap_Rnotebook_example.Rmd) However I don't seem to be able to find the mammoth data (as stated [mammoth dataset](https://github.com/PAIR-code/understanding-umap/tree/master/raw_data)).

`data <- read.csv("mammoth_data.csv")`

Thank you,
Pearl

**Comment by hyhuang00** [comment]
Hi Pearl, thank you for your interest in PaCMAP! The sample data has been uploaded [here](https://github.com/YingfanWang/PaCMAP/blob/master/demo/mammoth_data.csv).

**Comment by wichaidi** [comment]
Thank you so much!
