### ISSUE TITLE
Two possible bugs in `sample_FP_pair` and `sample_FP_pair_deterministic`

### ISSUE THREAD

**Issue by Wainberg** [YingfanWang/PaCMAP#75]
PaCMAP is such a neat tool, thanks for making it available to the community!

It looks like there may be two bugs in `sample_FP_pair` and `sample_FP_pair_deterministic`. For instance, the loop body of `sample_FP_pair_deterministic` is:

```python
for i in numba.prange(n):
    for k in numba.prange(n_FP):
        np.random.seed(random_state+i*n_FP+k)
        FP_index = sample_FP(
            n_FP, n, pair_neighbors[i*n_neighbors: i*n_neighbors + n_neighbors][1])
        pair_FP[i*n_FP + k][0] = i
        pair_FP[i*n_FP + k][1] = FP_index[k]
```

I think it should be:

```python
for i in numba.prange(n):
    np.random.seed(random_state+i)
    FP_index = sample_FP(
        n_FP, n, np.concatenate([[i], pair_neighbors[i*n_neighbors: i*n_neighbors + n_neighbors][:, 1]]))
    for k in numba.prange(n_FP):
        pair_FP[i*n_FP + k][0] = i
        pair_FP[i*n_FP + k][1] = FP_index[k]
```

Where:
1. `sample_FP` is moved outside the inner loop. Currently, for each iteration of the `k` loop, you randomly sample `n_FP` further pairs, only to discard all but the `k`th. This is inefficient and also risks sampling the same further pairs multiple times.
2. The second index on `pair_neighbors` is `[:, 1]` rather than `[1]`, and `i` itself is included via the `np.concatenate()`. (There are more efficient ways than concatenate, I'm just including it for illustrative purposes.) Currently, it seems like you only exclude two points from consideration when randomly generating further pairs: `pair_neighbors[i * n_neighbors + 1, 0]`, which is just `i`, and `pair_neighbors[i * n_neighbors + 1, 1]`, which is one of `i`'s nearest neighbors. But `i`'s other `n_neighbors - 1` nearest neighbors are not being excluded from consideration, and may be erroneously selected as further pairs.

**Comment by Wainberg** [comment]
I think there may be a third bug as well, in `sample_FP`: 

```python
while reject_sample:
    j = np.random.randint(maximum)
    for k in range(i):
        if j == result[k]:
            break
    for k in range(reject_ind.shape[0]):
        if j == reject_ind[k]:
            break
    else:
        reject_sample = False
```

I think it should be:

```python
while reject_sample:
    j = np.random.randint(maximum)
    for k in range(i):
        if j == result[k]:
            break
    else:
        for k in range(reject_ind.shape[0]):
            if j == reject_ind[k]:
                break
        else:
            reject_sample = False
```

Currently, the `j == result[k]` test is effectively ignored, allowing the same points to be sampled multiple times.

**Comment by hyhuang00** [comment]
Thanks for reporting! There might be some unexpected change in the logic for the deterministic version due to the usage of explicit numpy seed usage, and they should be fixed. I am of limited bandwidth at this moment, and I will try my best to check them the following weekend.

**Comment by Wainberg** [comment]
Sounds good. The issue isn't specific to the deterministic version, it's present in both.

I think there's also a bug in `sample_MN_pair()` and `sample_MN_pair_deterministic()` where there's no check that the sampled points (`sampled = np.random.randint(0, n, 6)`) are not equal to `i`. That makes it possible to sample pairs where the two cells in the pair are the same:

```
>>> X.shape
(1630, 50)
>>> a = sample_MN_pair(X, 100, option=0); a.std(axis=1).min()
0.0
>>> a
array([[   0, 1267],
       [   0, 1515],
       [   0,   85],
       ...,
       [1629, 1046],
       [1629,   35],
       [1629,  499]], dtype=int32)
>>> np.flatnonzero(a[:, 0] == a[:, 1])
array([ 25818, 139014])
>>> a[25818]
array([258, 258], dtype=int32)
```

**Comment by hyhuang00** [comment]
I read the related functions again and can confirm these concerns are valid. Fixes have been proposed in the hotfix branch and I'm currently testing whether these fixes solve the problem. Thanks for reporting!
