### ISSUE TITLE
"Killed" happening while fitting large dataset

### ISSUE THREAD

**Issue by FlimFlamm** [YingfanWang/PaCMAP#77]
I'm getting terminal killed print; not sure why yet (memory usage seems good, but CPU usage is pretty much maxed out).

Here's the snipped:

```py
import pacmap
import numpy as np

# shape is (9268108, 3584)
# dtype is float32
X = np.load("X.npy", mmap_mode="r")

n, dim = X.shape
n_neighbors = 10

scaled_dist = np.ones((n, n_neighbors)) # No scaling is needed

scaled_dist = scaled_dist.astype(np.float32)

# shape is (9268108, 2)
# dtype is int32
pair_neighbors = np.load("pair_neighbors.npy", mmap_mode="r")

embedding = pacmap.PaCMAP(n_components=2, n_neighbors=n_neighbors, MN_ratio=0.5, FP_ratio=2.0, pair_neighbors=pair_neighbors, verbose=True, apply_pca=True) 

X_transformed = embedding.fit_transform(X, init="pca") # <-- killed here
```

Wondering if there's anything obvious I'm doing or not doing would run afoul of the fitting process.. It's not hitting "iterations" at all or reporting any loss...

It's also not lost on me that this is a rather large dataset. Assuming the memory requirements are simply too large here and i can do nothing about it, how could I calculate an appropriate embedding dimensionality to downcast the dataset into? (whether by PCA autoencoder or something else)

EDIT: was getting killed messages due to out-of-memory issues caused by the large dataset (my resources monitoring was deceptive due to a weirdly containerized remote machine). See https://github.com/YingfanWang/PaCMAP/issues/77#issuecomment-2287858613 for the gist of the steps I took to overcome the issues caused by this large a dataset with this large a dimensionality.

**Comment by hyhuang00** [comment]
It's hard to tell -- the dataset is very big and the dimensionality is also high here. I only tried dataset as large as ~2M. Nevertheless, the memory consumption should still be manageable. I noticed that you set verbose=True when initializing PaCMAP instance. Do you know which stage your script was killed?

**Comment by FlimFlamm** [comment]
> It's hard to tell -- the dataset is very big and the dimensionality is also high here. I only tried dataset as large as ~2M. Nevertheless, the memory consumption should still be manageable. I noticed that you set verbose=True when initializing PaCMAP instance. Do you know which stage your script was killed?

Thanks for the reply!

It happens before any of the verbose prints, so before preprocess_X() (the X is normalized print) as far as I can tell. Adding a whack of prints to try and determine the kill point now.

I'd be forever thankful if you could give me any tips re: this use case. Will give a more detailed crash report ASAP!

**Comment by hyhuang00** [comment]
Oh I see. I guess the problem is within the PCA initialization, where the memory consumption can be huge (O(N^2)). Unfortunately PCA is currently hard-coded into PaCMAP so I don't have a solution that's immediately ready -- perhaps you can try downsampling your data by sample 1/10th data points out of it.

**Comment by FlimFlamm** [comment]
Looks like the killing line was at the start of `PaCMAP.fit()`:

```py
X = np.copy(X).astype(np.float32)
```

https://github.com/YingfanWang/PaCMAP/blob/3637bc5735f21c50718c90b914eec71f173a9654/source/pacmap/pacmap.py#L877

I'm guessing this was a defensive measure? Commenting this out allows me to start prepossessing X function, so will wait to see how this goes and report back with results! (the PCA will probably take a while before possibly failing).

RE: subsets vs pre-dimensionality reduction

Taking a subset of the data is definitely an option but i'd probably prefer to downsample the embedding dim first. I can certainly bring my own PCA model (would embedding my dataset into a lower dim PCA and then putting it through PaCMAP with init="pca" turned off essentially be equivalent to having it turned on?). I'm also interested in other kinda of dim-reducers.

Any idea what a safe or optimal dimension to aim for might be in general? Any idea how to estimate memory usage given a dataset length and component count?

PaCMAP looks like the highest quality dimensionality reducer so I'm going to give it my effort to make it work for this case! (advice always appreciated!)

**Comment by hyhuang00** [comment]
Yes, this is a defensive measure as our functions are set to work only for fp32. It could be possible that your machine is running out of memory since your data is huge.

Regarding the dimension, I would suggest try to do dimension=100 for a first trial, but the number of dimension really depends on the type of data you are working with, so additional experiments are required.

**Comment by FlimFlamm** [comment]
> Yes, this is a defensive measure as our functions are set to work only for fp32. It could be possible that your machine is running out of memory since your data is huge.
> 
> Regarding the dimension, I would suggest try to do dimension=100 for a first trial, but the number of dimension really depends on the type of data you are working with, so additional experiments are required.

Managed to get the job done in the end, and in fairly reasonable wall clock time...

Tricks:

1) prepare the annoy tree before hand (the longest part of the process)
2) multiprocess-compute top-k-neighbors for the whole dataset with the annoy tree
3) precompute neighbor/MN/FP pairs
4) precompute an incremental PCA and get the embedding initialization (Yinit)
5) Pytorch-ify the final pacmap optimization loop (pacmap_grad(), update_embedding_adam(), pacmap())

Running the final optimization loop with large batch size on GPU via pytorch was the biggest time save (turns the task from hundreds of hours to tens of minutes!). Some of these pre-compute steps aren't absolutely necessary memory-wise (eg: I could still compute a PCA/top-k-neighbors/neighbor pairs at run time to get the init, but memory has to be carefully managed and cleaned, and if something goes wrong or the process needs to be restarted, the wait time became extreme.

Having all the bits nicely pre-prepared also means that I can re-run the optimization steps with different hyperparams to try and improve results (20 minutes on an H100).

I still have some experimenting to do with those various hyper-params (eg. n_neighbors, lr, iterations-per-phase, etc); not yet sure how everything ends up impacting the memory and wall-clock performance of the final loop, but it's surprisingly lean for this dataset once all the heavy lifting is precomputed.

Got any tips or insights that might be relevant to my big data use-case?

Here's what 9.6M embedded text documents ended up looking like (2-Dim pacmap, colored by a 3-dim PCA transformation) 

![pacmap_embedding_rgb](https://github.com/user-attachments/assets/e6411ada-5c4f-4885-ab53-a976c59553e0)

**Comment by FlimFlamm** [comment]
Closing due to issue resolved (described above)
