### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by Gasp34** [YingfanWang/PaCMAP#85]
The readme says that init default to random : 

> init: the initialization of the lower dimensional embedding. One of "pca" or "random", or a user-provided numpy ndarray with the shape (N, 2). Default to "random".

While the code says it default to "pca"
```
init: str, optional
            One of ['pca', 'random']. Initialization of the embedding, default='pca'.
```

**Comment by hyhuang00** [comment]
Thank you for catching the problem! The readme should have been fixed now.
